name: Shared Setup

on:
  workflow_call:
    secrets:
      GOOGLE_MAPS_API_KEY:
        required: true

jobs:
  setup:
    name: ðŸ› ï¸ Shared Setup
    runs-on: ubuntu-latest
    steps:
    - name: Create .env file
      run: |
        touch .env
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env

    - name: Upload .env file
      uses: actions/upload-artifact@v4
      with:
        name: env-file
        include-hidden-files: true
        path: .env